### ISSUE TITLE
cdk deploy fails

### ISSUE THREAD

**Issue by ekimike** [stratospheric-dev/stratospheric#69] opened 2021-11-09 03:51 UTC
### What's going wrong and not working?

for Chapter 5. Page 72 says we can run CDK deploy just with the required code but at the end, the command fails because it starts failing on Service.java (74), then. SpringBootApplicationStack.java(32) both of them from the stratospheric maven library. It seems it fails because on SpringBootApplicationStack.java line 26, the fifth argument building the Network.NetworkInputParameters() is using that empty constructor, which means we are not going to use SslCertifcateArn:

```java
Caused by: java.util.NoSuchElementException: No value present
    at java.util.Optional.get (Optional.java:141)
    at dev.stratospheric.cdk.Service.<init> (Service.java:74)
    at dev.stratospheric.cdk.SpringBootApplicationStack.<init> (SpringBootApplicationStack.java:32)
    at com.myorg.MyCdkApp.main (MyCdkApp.java:29)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:832)
```

Line 29 form MyCdkApp.java is

```java       
 new SpringBootApplicationStack(
          app,
          "SpringBootApplication",
          makeEnv(accountId, region),        //line 29
          "docker.io/stratospheric/todo-app-v1:latest"
        );
```

### Expected outcome

Cloudformation built from CDK

**Comment by BjoernKW** [comment] 2021-11-15 17:16
Thanks for reporting this issue. This essentially the same issue as the one described here: https://github.com/stratospheric-dev/stratospheric/issues/59

The issue is caused by the HTTPS listener not yet being present at that point, which leads to the exception mentioned above when trying to access `httpsListenerArn` in line 74 of `Service.java`.

We're currently working a consistent solution.

**Comment by BjoernKW** [comment] 2021-11-15 17:17
Duplicate of https://github.com/stratospheric-dev/stratospheric/issues/59

**Closed by BjoernKW** 2021-11-15 17:17 UTC
Labels: application-feedback, triage
